language: go

script:
  - make build
  - make
  - make image

deploy:
  - provider: script
    skip_cleanup: true
    script: >
      bash -c '
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push nfvpe/sriov-device-plugin'
    on:
      branch: master
  - provider: script
    script: >
      bash -c '
      docker tag nfvpe/sriov-device-plugin nfvpe/sriov-device-plugin:release-v1;
      docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS";
      docker push nfvpe/sriov-device-plugin:release-v1'
    on:
      branch: release-v1
