language: go

script:
  - make build
  - make
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push nfvpe/sriov-device-plugin:latest
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      - docker tag nfvpe/sriov-device-plugin nfvpe/sriov-device-plugin:release-v1
    on:
      branch: release-v1
