language: go

script:
  - make build
  - make
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag nfvpe/sriov-device-plugin zenghui/sriov-device-plugin

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push zenghui/sriov-device-plugin
    on:
      branch: master
